---
title: "Effect of Population Density on Life Expectancy"
author: "Julia Du"
date: "`r lubridate::today()`"
output: 
  github_document:
    toc: true
---

## ADD A SETUP CHUNK LATER

## Load necessary libraries

```{r, message = FALSE}
library(tidyverse)
library(rcfss)
library(lubridate)
library(geonames)
library(countrycode)
library(gapminder)

#set.seed(123)

theme_set(theme_minimal())


```

## country info from geonames
```{r}
countryInfo <- GNcountryInfo()
# we know this countryInfo df from geonames stores countries using the iso2c format
gap <- gapminder


#countryInfo$countryName <- countrycode(countryInfo$countryName, origin = "country.name", destination = "iso3c")

gap$country <- countrycode(gap$country, origin = "country.name", destination = "iso2c")

countryInfo <- countryInfo %>%
  mutate(areaInSqKm = as.numeric(areaInSqKm)) %>%
  rename(area = areaInSqKm, country = countryCode)


# want to calculate pop density
# gap gives lifeExp & population - throughout multiple points in time. so it has multiple rows for each country

# countryInfo gives population & sq area for ONE time. has 1 row for each country 
joined_country <- left_join(gap, countryInfo, by = "country") %>%
  mutate(popdensity = pop/area) 

```


```{r graphs}
joined_country %>%
  ggplot(mapping = aes(x = popdensity, y = lifeExp)) +
  geom_point(aes(color = continent.x), alpha = 0.2) +
  geom_smooth() + 
  labs(title = "As population density increases, life expectancy typically increases", x = "Population density \n(people per square km)", y = "Average life expectancy", color = "Continent")

joined_country %>%
  ggplot(mapping = aes(x = popdensity, y = lifeExp)) +
  geom_point(alpha = 0.2) +
  geom_smooth(aes(color = continent.x)) +
  facet_wrap(~ continent.x, scales = "free") +
  labs(title = "As population density increases, life expectancy typically increases", x = "Population density \n(people per square km)", y = "Average life expectancy", color = "Continent")
```


```{r}

```


```{r}

```

## Session info

```{r, echo = TRUE}
devtools::session_info()
```
